### ISSUE TITLE
Poetry add fails with Cython not found

### ISSUE THREAD

**Issue by SebastianoF** [martinfleis/xyzdata#22]
```bash
$ poetry add geodataset
Using version ^0.3.0 for geodataset

Updating dependencies
Resolving dependencies... (3.4s)

Package operations: 10 installs, 0 updates, 0 removals

  - Installing cftime (1.6.4)
  - Installing configobj (5.0.8)
  - Installing cython (3.0.10)
  - Installing donfig (0.8.1.post1)
  - Installing pykdtree (1.3.12)
  - Installing netcdf4 (1.7.1.post1)
  - Installing netcdftime (1.0.0a2): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "/Users/sebastianoferraris/.local/pipx/venvs/poetry/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
      main()
    File "/Users/sebastianoferraris/.local/pipx/venvs/poetry/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/sebastianoferraris/.local/pipx/venvs/poetry/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 134, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/rv/5w5ms4g91sbdd2q8_60bphqr0000gn/T/tmpqi5obl79/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/rv/5w5ms4g91sbdd2q8_60bphqr0000gn/T/tmpqi5obl79/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/rv/5w5ms4g91sbdd2q8_60bphqr0000gn/T/tmpqi5obl79/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
      super().run_setup(setup_script=setup_script)
    File "/private/var/folders/rv/5w5ms4g91sbdd2q8_60bphqr0000gn/T/tmpqi5obl79/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 3, in <module>
  ModuleNotFoundError: No module named 'Cython'
  

  at ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with netcdftime (1.0.0a2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "netcdftime (==1.0.0a2)"'.

  - Installing pyresample (1.28.4)
  - Installing xarray (2024.6.0)
 ```

This is still not working even after `pip3 install Cython`. 
The problem is that, as stated, `netcdftime` does not support PEP 517 (thing that can be verified with `pip wheel --no-cache-dir --use-pep517 "netcdftime (==1.0.0a2)"`).  

I guess the solution is to downgrade python?

Is there any other workaround or plan to avoid using `netcdftime`, that looks an abandoned project https://pypi.org/project/netcdftime/#description ?

--------

On a sidenote, with the same environment manager (poetry, python 3.12), I can install `geopandas==0.14.4` and run `gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))` with no issues.

**Comment by martinfleis** [comment]
you have a typo in your command. It shall be geodataset**s**, not geodataset. We do not depend on `netcdftime`

```
poetry add geodatasets
```

**Comment by SebastianoF** [comment]
Thanks! I was running in circle to try to understand where the `netcdftime` was included in the requirements 🤦
